// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@noversystem.dev"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Mengotentikasi pengguna dengan username dan password, lalu memberikan JWT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login pengguna",
                "parameters": [
                    {
                        "description": "Kredensial Login dengan Username",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Input tidak valid",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Kredensial tidak valid",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error internal server",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Membuat akun pengguna baru dengan email, username, dan password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Registrasi pengguna baru",
                "parameters": [
                    {
                        "description": "Informasi Registrasi Pengguna",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tables.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/tables.User"
                        }
                    },
                    "400": {
                        "description": "Input tidak valid",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Email atau Username sudah terdaftar",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error internal server",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/authors/:authorId/books": {
            "get": {
                "description": "Mengambil daftar semua buku dari seorang penulis berdasarkan ID penulis.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "Dapatkan Buku Berdasarkan Penulis (Publik)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID dari Penulis",
                        "name": "authorId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.BookListResponse"
                        }
                    },
                    "400": {
                        "description": "ID Penulis tidak valid",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error internal server",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/bank/get": {
            "get": {
                "description": "Mengambil daftar semua bank yang aktif, diurutkan berdasarkan nama.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bank"
                ],
                "summary": "Daftar Bank",
                "responses": {
                    "200": {
                        "description": "Daftar bank yang berhasil diambil",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.BankResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Terjadi kesalahan internal pada server",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/v1/books/:bookId/complete": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Mengubah status buku menjadi 'Completed'. Hanya bisa dilakukan pada buku yang sedang 'Published'.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book Management"
                ],
                "summary": "Selesaikan Buku",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Buku",
                        "name": "bookId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "code": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/books/:bookId/hold": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Mengubah status buku menjadi 'On Hold'.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book Management"
                ],
                "summary": "Tunda Buku",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Buku",
                        "name": "bookId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "code": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/books/:bookId/publish": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Mengubah status buku menjadi 'Published'. Memerlukan minimal 1 chapter.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book Management"
                ],
                "summary": "Publikasikan Buku",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Buku",
                        "name": "bookId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "code": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/books/:bookId/unpublish": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Mengubah status buku kembali menjadi 'Draft'. Hanya bisa dilakukan pada buku yang sedang 'Published'.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book Management"
                ],
                "summary": "Batalkan Publikasi Buku",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Buku",
                        "name": "bookId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "code": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/books/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Membuat buku baru oleh pengguna yang sudah terotentikasi dan berstatus sebagai penulis.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "Buat Buku Baru",
                "parameters": [
                    {
                        "description": "Data buku yang akan dibuat",
                        "name": "book_data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateBookRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/tables.Book"
                        }
                    },
                    "403": {
                        "description": "Akses ditolak (bukan penulis)",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/books/my-books": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Mengambil daftar semua buku yang ditulis oleh pengguna yang sedang login.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book"
                ],
                "summary": "Dapatkan Buku Saya (Pribadi)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.BookListResponse"
                        }
                    },
                    "401": {
                        "description": "Tidak terotentikasi",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error internal server",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/books/{bookId}/chapters": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Menambahkan sebuah chapter baru ke buku yang sudah ada. Pengguna harus menjadi pemilik buku tersebut.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chapter"
                ],
                "summary": "Tambah Chapter Baru",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Buku",
                        "name": "bookId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data chapter yang akan dibuat",
                        "name": "chapter_data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateChapterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/tables.Chapter"
                        }
                    },
                    "400": {
                        "description": "Input tidak valid",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Tidak terotentikasi",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Akses ditolak (bukan pemilik buku)",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Buku tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error internal server",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/books/{bookId}/detail": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Mengambil detail lengkap sebuah buku, termasuk daftar chapternya. Hanya bisa diakses oleh penulis buku tersebut.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Book Management"
                ],
                "summary": "Dapatkan Detail Buku Saya",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Buku",
                        "name": "bookId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tables.BookDetailResponse"
                        }
                    },
                    "401": {
                        "description": "Tidak terotentikasi",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Bukan pemilik buku",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Buku tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error internal server",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/genres": {
            "get": {
                "description": "Mengambil daftar semua genre yang tersedia dan aktif di sistem.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Genre"
                ],
                "summary": "Dapatkan Semua Genre Aktif",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.GenreListResponse"
                        }
                    },
                    "500": {
                        "description": "Error internal server",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/user/author-status": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Memvalidasi token, memeriksa apakah pengguna adalah penulis, dan mengembalikan data profil lengkap pengguna.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Cek Status Penulis \u0026 Profil",
                "responses": {
                    "200": {
                        "description": "Status penulis dan data profil lengkap",
                        "schema": {
                            "$ref": "#/definitions/controllers.AuthorStatusResponse"
                        }
                    },
                    "401": {
                        "description": "Tidak terotentikasi",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Pengguna tidak ditemukan",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error internal server",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/user/request-author": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Memperbarui profil pengguna untuk menjadi penulis dengan melengkapi data yang diperlukan. Endpoint ini memerlukan otentikasi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Permintaan menjadi Penulis",
                "parameters": [
                    {
                        "description": "Data untuk menjadi penulis",
                        "name": "author_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.AuthorRequestPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pesan sukses",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "code": {
                                    "type": "string"
                                },
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Input tidak valid",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Tidak terotentikasi",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Nama pena sudah digunakan",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error internal server",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.AuthorRequestPayload": {
            "type": "object",
            "properties": {
                "accountNumber": {
                    "type": "string"
                },
                "bankId": {
                    "type": "integer"
                },
                "instagram": {
                    "type": "string"
                },
                "penName": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "controllers.AuthorStatusResponse": {
            "type": "object",
            "properties": {
                "isAuthor": {
                    "type": "boolean"
                },
                "user": {
                    "$ref": "#/definitions/tables.User"
                }
            }
        },
        "controllers.BankResponse": {
            "type": "object",
            "properties": {
                "bankCode": {
                    "type": "string"
                },
                "bankId": {
                    "type": "integer"
                },
                "bankName": {
                    "type": "string"
                }
            }
        },
        "controllers.BookListResponse": {
            "type": "object",
            "properties": {
                "bookList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tables.Book"
                    }
                }
            }
        },
        "controllers.CreateBookRequest": {
            "type": "object",
            "properties": {
                "coverImageUrl": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "genreIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "controllers.CreateChapterRequest": {
            "type": "object",
            "properties": {
                "coinCost": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "controllers.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "controllers.GenreListResponse": {
            "type": "object",
            "properties": {
                "genreList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tables.Genre"
                    }
                }
            }
        },
        "controllers.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "username": {
                    "type": "string",
                    "example": "testuser"
                }
            }
        },
        "controllers.LoginSuccessResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/tables.User"
                }
            }
        },
        "fiber.Map": {
            "type": "object",
            "additionalProperties": true
        },
        "tables.Book": {
            "type": "object",
            "properties": {
                "bookId": {
                    "type": "integer"
                },
                "coverImageUrl": {
                    "type": "string"
                },
                "createDatetime": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "genres": {
                    "type": "string"
                },
                "ratingAverage": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "totalViews": {
                    "type": "integer"
                },
                "updateDatetime": {
                    "type": "string"
                }
            }
        },
        "tables.BookDetailResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/tables.User"
                },
                "bookInfo": {
                    "$ref": "#/definitions/tables.Book"
                },
                "chapters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tables.Chapter"
                    }
                }
            }
        },
        "tables.Chapter": {
            "type": "object",
            "properties": {
                "bookId": {
                    "type": "integer"
                },
                "chapterId": {
                    "type": "integer"
                },
                "chapterOrder": {
                    "type": "integer"
                },
                "coinCost": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "createDatetime": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "totalViews": {
                    "type": "integer"
                },
                "updateDatetime": {
                    "type": "string"
                }
            }
        },
        "tables.Genre": {
            "type": "object",
            "properties": {
                "activeDatetime": {
                    "type": "string"
                },
                "createDatetime": {
                    "type": "string"
                },
                "genreId": {
                    "type": "integer"
                },
                "genreName": {
                    "type": "string"
                },
                "genreTl": {
                    "type": "string"
                },
                "nonActiveDatetime": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "updateDatetime": {
                    "type": "string"
                }
            }
        },
        "tables.User": {
            "type": "object",
            "properties": {
                "accountNumber": {
                    "type": "string"
                },
                "avatarUrl": {
                    "type": "string"
                },
                "bankId": {
                    "type": "integer"
                },
                "createDatetime": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "flgAuthor": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "instagram": {
                    "type": "string"
                },
                "isEmailVerified": {
                    "type": "boolean"
                },
                "loginWith": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "penName": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "updateDatetime": {
                    "type": "string"
                },
                "userCode": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Nover System API",
	Description:      "Ini adalah dokumentasi API untuk Nover System.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
